name: Run test
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-2022, macos-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./converter
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup and execute Gradle 'test' task
        run: chmod +x gradlew
      - name: Testing
        run: ./gradlew test

